### ISSUE TITLE
Does not work for latest Rollbar version.

### ISSUE THREAD

**Issue by zbigniew-klasik** [olsh/serilog-sinks-rollbar#5]
It works fine for Rollbar version 1.6.2 (this is the last 1.* version of Rollbar). 

From Rollbar version 2.0.0 and later (now the latest is 2.1.1) when configuring sink .WriteTo.Rollbar(...) there is:

**Exception: Entry point was not found.**

   at Rollbar.ILogger.AsBlockingLogger(TimeSpan timeout)
   at Serilog.RollbarSink..ctor(String accessToken, String environment, IFormatProvider formatProvider, Action`1 transform, String proxyAddress, String[] scrubFields, Boolean asyncLogging, TimeSpan asyncLoggingTimeout)
   at Serilog.RollbarSinkExtensions.Rollbar(LoggerSinkConfiguration loggerConfiguration, String accessToken, String environment, LogEventLevel restrictedToMinimumLevel, IFormatProvider formatProvider, Action`1 transform, String proxyAddress, String[] scrubFields, Boolean asyncLogging, TimeSpan asyncLoggingTimeout)

**Comment by olsh** [comment]
Thank you for the reporting.
The issues fixed in 1.0.3.
